export const superheroes = [
    { id: "1", name: "A-Bomb" },
    { id: "2", name: "Abe Sapien" },
    { id: "3", name: "Abin Sur" },
    { id: "4", name: "Abomination" },
    { id: "5", name: "Abraxas" },
    { id: "6", name: "Absorbing Man" },
    { id: "7", name: "Adam Monroe" },
    { id: "8", name: "Adam Strange" },
    { id: "9", name: "Agent 13" },
    { id: "10", name: "Agent Bob" },
    { id: "11", name: "Agent Zero" },
    { id: "12", name: "Air-Walker" },
    { id: "13", name: "Ajax" },
    { id: "14", name: "Alan Scott" },
    { id: "15", name: "Alex Mercer" },
    { id: "16", name: "Alex Woolsly" },
    { id: "17", name: "Alfred Pennyworth" },
    { id: "18", name: "Alien" },
    { id: "19", name: "Allan Quatermain" },
    { id: "20", name: "Amazo" },
    { id: "21", name: "Ammo" },
    { id: "22", name: "Ando Masahashi" },
    { id: "23", name: "Angel" },
    { id: "24", name: "Angel" },
    { id: "25", name: "Angel Dust" },
    { id: "26", name: "Angel Salvadore" },
    { id: "27", name: "Angela" },
    { id: "28", name: "Animal Man" },
    { id: "29", name: "Annihilus" },
    { id: "30", name: "Ant-Man" }
  ];